# Generated by Django 3.2.2 on 2021-08-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://www.salonlfc.com/wp-content/uploads/2018/01/image-not-found-scaled-1150x647.png', max_length=240),
        ),
    ]
